name: Whitelister
version: '1.0-BETA'
main: pl.re1.whitelister.Whitelister
api-version: '1.20'

commands:
  whitelister:
    description: Allows or denies players joining on the list (better whitelist)
    usage: /whitelister <allow | deny> <user>
    permission: whitelister.manage

permissions:
  whitelister.manage:
    description: Allows users to manage whitelist
    default: op
  whitelister.see:
    description: Allows users to see whitelist
    default: not op
